### ISSUE TITLE
Incorrect date on notifications

### ISSUE THREAD

**Issue by BogDAAAMN** [thepracticaldev/dev.to#3183]
**Describe the bug**

Opening the notification panel, I see wrong dates for the notification that I get. It's not clear if the date should show when the post or the notification was created, but either way, they also never change (see the comparison on screenshots Jun 15 vs Jun 16).

**To Reproduce**

1. Go to https://dev.to/notifications.
2. See a _someone made a new post_ notification.
3. Check the date of the notification (eg _less than a minute ago_).

**Expected behavior**

To update the date of the notification/post.

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Firefox 7.0.2 (64-bit)

_Checked on Chrome 74.0.3729.169 (Official Build) (64-bit) as well._

![Mozzila 7.0.2 (64-bit)](https://user-images.githubusercontent.com/22895284/59566480-17617080-9061-11e9-95d5-e7ccdab8a13d.jpg)

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy S7
- OS: Android 8.0.0
- Browser: Chrome 74.0.3729.157

![two](https://user-images.githubusercontent.com/22895284/59566503-79ba7100-9061-11e9-8d55-49ea892a3229.jpg)

**Comment by Glennmen** [comment]
That is the time when the notification was created and not when the article was published, btw there is an issue already about this topic 😉https://github.com/thepracticaldev/dev.to/issues/2997

**Comment by BogDAAAMN** [comment]
> That is the time when the notification was created and not when the article was published, btw there is an issue already about this topic 😉#2997

Yeah, but checking the same notification (see **What's your worst nightmare as a coder?**) in different days I got the same timestamp of _less than a minute ago_.

**Comment by maestromac** [comment]
Hello @BogDAAAMN This should be resolved by https://github.com/thepracticaldev/dev.to/pull/3076 Can you help us verify that?

**Comment by mazentouati** [comment]
@maestromac that PR has been merged yesterday, it should be live now. However, it does not fixes the frozen timestamps. Are they cached ?

**Comment by BogDAAAMN** [comment]
@maestromac @mazentouati the PR seems the fix the issue for me. Though I get random notifications with _1 minute ago_ timestamp in the middle of the list. I will monitor the status of these cases and see if they change.

**Comment by rhymes** [comment]
@BogDAAAMN they are all cached, so it might take a while

**Comment by shreyasminocha** [comment]
I think I still see incorrect dates in my notifications.

![screenshot 2019-07-14 at 9 27 05 PM](https://user-images.githubusercontent.com/11537232/61186043-0ef45980-a650-11e9-9fa0-7c3582db6bba.jpg)
