### ISSUE TITLE
Markdown doesn't highlight code after some time

### ISSUE THREAD

**Issue by wolfiton** [thepracticaldev/dev.to#6665]
**Describe the bug**

Look at this article https://dev.to/wolfiton/absinthe-journey-with-wolfiton-or-how-to-bring-the-absinthe-tutorial-up-to-date-part-7-the-user-58

**To Reproduce**
Write normal markdown for an article and then after some time you will get this https://dev.to/wolfiton/absinthe-journey-with-wolfiton-or-how-to-bring-the-absinthe-tutorial-up-to-date-part-7-the-user-58

A markdown article that has working code highlight 

Please inspect the source code of the article for any in-depth info and more traces of the bug.

https://dev.to/wolfiton/absinthe-journey-with-wolfiton-or-how-to-bring-the-absinthe-tutorial-up-to-date-part-7-the-user-58

Gist with the source code

https://gist.github.com/wolfiton/192e67588e8e9d8a0591e7f86316a6f1

**Comment by rhymes** [comment]
Hi @wolfiton, could you paste your markdown in a Gist - https://gist.github.com/new - and then link it here?

**Comment by wolfiton** [comment]
Hi @rhymes 

Thanks for the quick reply

The gist is here https://gist.github.com/wolfiton/192e67588e8e9d8a0591e7f86316a6f1

**Comment by rhymes** [comment]
Hi, there are two issues with that markdown that prevent rendering.

Between line 68 and 69 you need an empty line: https://gist.github.com/wolfiton/192e67588e8e9d8a0591e7f86316a6f1#file-gistfile1-txt-L68

on line 128 there's an extra backtick at the end of the line https://gist.github.com/wolfiton/192e67588e8e9d8a0591e7f86316a6f1#file-gistfile1-txt-L128

I fixed those and was able to render, let me know if that works for you!

**Comment by wolfiton** [comment]
Hi,
Still not working properly
Try to create a new article on dev and preview the article using the gist raw data.

**Comment by rhymes** [comment]
I did, after fixing the two errors. Check this gist - https://gist.github.com/rhymes/ca47ec77e64a7b8ee6bfb83b1dafb44c - which is the markdown and the following screenshot

![Screenshot_2020-03-16 elixir post - DEV(local) Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/76780966-3d61a000-67ae-11ea-8295-0eca5ca51525.png)

If you look closely at the gist show page you'll notice it's correctly rendered by Github as well

**Comment by rhymes** [comment]
Let me know if I missed something, thanks!

**Comment by wolfiton** [comment]
Hi,
My markdown editor is it seems that it didn't show the extra ` and also the space that was needed. I will probably have to change it to vscodium.

Thanks @rhymes  your post.md template with raw data worked.
